### ISSUE TITLE
Replace react-scripts-ts

### ISSUE THREAD

**Issue by numo16** [plexsystems/rabbit-viz#1]
This project currently uses [react-scripts-ts](https://github.com/wmonk/create-react-app-typescript), which has been deprecated. Create react app now natively supports typescript and should be used from here on out.

Here is a helpful guide for migrating from react-scripts-ts to react-scripts: https://vincenttunru.com/migrate-create-react-app-typescript-to-create-react-app/

**Comment by jpreese** [comment]
As an aside, this should also resolve the vulnerability notice from github relating to webpack-dev-server
