### ISSUE TITLE
Add a sample broker definition to https://plexsystems.github.io/rabbit-viz/

### ISSUE THREAD

**Issue by luissantos** [plexsystems/rabbit-viz#13]
Add some sample configuration so that new users can understand better the value of this tool. 
I opened the page and could not find a sample configuration or a screenshot.

**Comment by numo16** [comment]
Thanks for the idea @luissantos! This is a great idea that would improve the immediate understanding of the tool and should be fairly easy to implement.

**Comment by numo16** [comment]
I can take this one on if nobody else is interested.

**Comment by numo16** [comment]
The implementation of this that I'm putting together is fairly simple, but should demonstrate the basics. The sample definition looks like this:

```json
{
  "vhosts": [{
    "name": "logs"
  }],
  "policies": [{
    "vhost": "logs",
    "name": "logs",
    "pattern": ".*",
    "apply-to": "all",
    "definition": {
      "ha-mode": "all",
      "ha-sync-mode": "manual"
    },
    "priority": 0
  }],
  "queues": [{
    "name": "log",
    "vhost": "logs",
    "durable": true,
    "auto_delete": false,
    "arguments": {}
  }, {
    "name": "critical",
    "vhost": "logs",
    "durable": true,
    "auto_delete": false,
    "arguments": {}
  }, {
    "name": "alert",
    "vhost": "logs",
    "durable": true,
    "auto_delete": false,
    "arguments": {}
  }],
  "exchanges": [{
    "name": "logs",
    "vhost": "logs",
    "type": "topic",
    "durable": true,
    "auto_delete": false,
    "internal": false,
    "arguments": {}
  }],
  "bindings": [{
    "source": "logs",
    "vhost": "logs",
    "destination": "log",
    "destination_type": "queue",
    "routing_key": "log.*",
    "arguments": {}
  }, {
    "source": "logs",
    "vhost": "logs",
    "destination": "critical",
    "destination_type": "queue",
    "routing_key": "*.critical",
    "arguments": {}
  }, {
    "source": "logs",
    "vhost": "logs",
    "destination": "alert",
    "destination_type": "queue",
    "routing_key": "alert.*",
    "arguments": {}
  }]
}
```
This produces a graph like this:
![image](https://user-images.githubusercontent.com/268388/53596799-9db77c80-3b6e-11e9-98ac-24dcae19ea4f.png)

This feels like a sufficient sample, without going full sample repository a la [ARMVIZ](http://armviz.io/designer), but I'm open to concerns/suggestions with this sample.

**Comment by jpreese** [comment]
I think it's a good enough start and better than we have right now (which is nada).

**Comment by numo16** [comment]
Example definition has been implemented and deployed to the gh-pages site.
